"""add embeddings

Revision ID: 2d6d4a6b4613
Revises: 8c122243395f
Create Date: 2026-06-28 19:42:02.118393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '2d6d4a6b4613'
down_revision: Union[str, Sequence[str], None] = '8c122243395f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # A fresh pgvector PostgreSQL database does not enable the extension merely
    # because the image ships it. The VECTOR column below requires it first.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_chunks', sa.Column('embedding', Vector(1536), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_chunks', 'embedding')
    # ### end Alembic commands ###
