"""Tunable constants for retrieval, ranking, and report relevance gates."""

MIN_EMBEDDING_SIMILARITY = 0.62
MIN_COMBINED_RETRIEVAL_SCORE = 0.30
EMBEDDING_FALLBACK_THRESHOLD = 0.68
MAX_CHUNKS_TO_RANKER = 50
MIN_CHUNKS_PER_ISSUE = 2
MAX_CHUNKS_PER_ISSUE = 12

# Retrieval-agent server bounds. Caller values are validated and then capped;
# these are not client-controlled tuning knobs.
RETRIEVAL_ENABLED_AGENTS = (
    "ContractAgent",
    "SupervisorManualAgent",
)
RETRIEVAL_MAX_QUERY_CHARS = 2_000
RETRIEVAL_DEFAULT_CANDIDATE_LIMIT = 48
RETRIEVAL_MAX_CANDIDATE_LIMIT = 96
RETRIEVAL_DEFAULT_PER_AGENT_RESULT_LIMIT = 8
RETRIEVAL_MAX_PER_AGENT_RESULT_LIMIT = 16
RETRIEVAL_DEFAULT_TOTAL_RESULT_LIMIT = 12
RETRIEVAL_MAX_TOTAL_RESULT_LIMIT = 24
RETRIEVAL_DEFAULT_PER_SOURCE_RESULT_LIMIT = 3
RETRIEVAL_MAX_PER_SOURCE_RESULT_LIMIT = 5
RETRIEVAL_MAX_SOURCE_DOMAINS = 2
RETRIEVAL_MAX_SOURCE_FILTERS = 16
RETRIEVAL_MAX_CHUNK_TEXT_CHARS = 6_000
RETRIEVAL_MAX_RESPONSE_TEXT_CHARS = 60_000
# Absolute candidate-admission floor before scoring. Final acceptance still
# requires the combined relevance threshold; this only excludes near-random
# vector neighbors so agents can score mid-similarity hits the same way the
# shared retrieval gate accepts strong combined scores.
RETRIEVAL_MIN_CANDIDATE_SIMILARITY = 0.45
RETRIEVAL_EMBEDDING_TIMEOUT_SECONDS = 20.0
RETRIEVAL_EMBEDDING_MAX_RETRIES = 1

# Legacy search_all fan-out budgets (per request). These cap intentional
# multi-query retrieval without inventing unbounded expansion.
LEGACY_MAX_DECOMPOSED_ISSUES = 8
LEGACY_MAX_QUERIES_PER_ISSUE = 6
LEGACY_MAX_GLOBAL_EXPANDED_QUERIES = 8
LEGACY_MAX_BACKFILL_QUERIES = 8
LEGACY_MAX_TOTAL_EMBEDDING_CALLS = 48
LEGACY_MAX_PROVIDER_CALLS = 128
LEGACY_MAX_TOTAL_CANDIDATE_CHUNKS = 500
LEGACY_MAX_LIMIT_PER_SOURCE = 8

MAX_AUTHORITIES_TO_RANKER = 15
MAX_DISTINCT_REPORT_AUTHORITIES = 5
MIN_AUTHORITIES_PER_DECOMPOSED_ISSUE = 1

MIN_AUTHORITY_RELEVANCE_SCORE = 65
MIN_KEY_AUTHORITY_RELEVANCE_SCORE = 75
MIN_MANAGEMENT_LIMITING_RELEVANCE_SCORE = 50

MIN_KEYWORD_OVERLAP_FOR_SUPPORTING = 0.15
MIN_KEYWORD_OVERLAP_FOR_MANAGEMENT = 0.08
MIN_KEYWORD_OVERLAP_RECLASSIFY_BACKGROUND = 0.10

EMBEDDING_SCORE_WEIGHT = 0.60
KEYWORD_SCORE_WEIGHT = 0.40

DIRECTION_CONTRADICTION_PENALTY = 0.25
SUBSTANTIVE_RULE_BONUS = 0.08
PROCEDURAL_ONLY_PENALTY = 0.12

SOURCE_TYPE_WEIGHTS = {
    "CONTRACT": 18,
    "CIM": 16,
    "ELM": 14,
    "LMOU": 14,
}

BOILERPLATE_PENALTY = 50.0
DEFAULT_SOURCE_WEIGHT = 8.0

TOPIC_MISMATCH_PENALTY_THRESHOLD = 0.75

REPORT_BRAND = "GrievanceHub"
REPORT_TITLE = "GrievanceHub Analysis Report"

RESEARCH_DRAFT_NOTICE = (
    "This GrievanceHub analysis is a research draft, not legal advice. "
    "Verify all citations, facts, and procedural steps before filing or "
    "presenting a grievance."
)
