"""Tunable constants for retrieval, ranking, and report relevance gates."""

MIN_EMBEDDING_SIMILARITY = 0.62
MIN_COMBINED_RETRIEVAL_SCORE = 0.30
EMBEDDING_FALLBACK_THRESHOLD = 0.68
MAX_CHUNKS_TO_RANKER = 50
MIN_CHUNKS_PER_ISSUE = 2
MAX_CHUNKS_PER_ISSUE = 12

MAX_AUTHORITIES_TO_RANKER = 15
MAX_DISTINCT_REPORT_AUTHORITIES = 5
MIN_AUTHORITIES_PER_DECOMPOSED_ISSUE = 1

MIN_AUTHORITY_RELEVANCE_SCORE = 65
MIN_KEY_AUTHORITY_RELEVANCE_SCORE = 75
MIN_MANAGEMENT_LIMITING_RELEVANCE_SCORE = 50

MIN_KEYWORD_OVERLAP_FOR_SUPPORTING = 0.15
MIN_KEYWORD_OVERLAP_FOR_MANAGEMENT = 0.08
MIN_KEYWORD_OVERLAP_RECLASSIFY_BACKGROUND = 0.10

EMBEDDING_SCORE_WEIGHT = 0.60
KEYWORD_SCORE_WEIGHT = 0.40

DIRECTION_CONTRADICTION_PENALTY = 0.25
SUBSTANTIVE_RULE_BONUS = 0.08
PROCEDURAL_ONLY_PENALTY = 0.12

SOURCE_TYPE_WEIGHTS = {
    "CONTRACT": 18,
    "CIM": 16,
    "ELM": 14,
    "LMOU": 14,
}

BOILERPLATE_PENALTY = 50.0
DEFAULT_SOURCE_WEIGHT = 8.0

TOPIC_MISMATCH_PENALTY_THRESHOLD = 0.75

REPORT_BRAND = "GrievanceHub"
REPORT_TITLE = "GrievanceHub Analysis Report"

RESEARCH_DRAFT_NOTICE = (
    "This GrievanceHub analysis is a research draft, not legal advice. "
    "Verify all citations, facts, and procedural steps before filing or "
    "presenting a grievance."
)
